Contacts
IgorPetrenko72/goiceteam-project pull request #20
Opened 2022-12-21 15:57 UTC by Ihor-M28

2022-12-21 16:26 UTC, IgorPetrenko72 approved these changes
ретельно не перевіряв ;)
тільки вирішив один конфлікт.

2022-12-21 16:28 UTC, Ihor-M28 commented
А що за конфлікт ??


ср, 21 груд. 2022, 18:26 користувач Igor Petrenko ***@***.***>
пише:

> ***@***.**** approved this pull request.
>
> ретельно не перевіряв ;)
> тільки вирішив один конфлікт.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/IgorPetrenko72/goiceteam-project/pull/20#pullrequestreview-1226390368>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3KKFT77XUIICVL2GCDA4MDWOMVSZANCNFSM6AAAAAATFY23OU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-12-21 16:35 UTC, IgorPetrenko72 commented
у index.html одна строка не відповідала main
можливо не оновилась

2022-12-21 16:53 UTC, IgorPetrenko72 commented on src/sass/components/_contacts.scss
> +.visually-hidden {
v-hidden є у reset

2022-12-21 16:55 UTC, IgorPetrenko72 reviewed
в мене на лайф сторінці  чомусь літери не відповідають макету

2022-12-21 22:57 UTC, YuliiaNivina approved these changes

2022-12-21 22:57 UTC, YuliiaNivina commented on src/sass/components/_contacts.scss
> +// }
Це код дублюється?
Ігорь, ми можемо це самі виправити, щоб якось цю секцію нарешті додати?

2022-12-21 22:57 UTC, YuliiaNivina commented on src/partials/contacts.html
> +  </div>
section не закрито?

2022-12-21 23:58 UTC, IgorPetrenko72 commented on src/sass/components/_contacts.scss
> +                #f9f7f7 50%,
думаю тут треба додати прозорість

2022-12-22 00:00 UTC, IgorPetrenko72 commented on src/sass/components/_contacts.scss
> +                #f9f7f7 20%,
також прозорісь

2022-12-22 00:05 UTC, IgorPetrenko72 requested changes
щє є якись проблеми з пзиціануванням - штовхаються з ревью.

2022-12-22 08:39 UTC, YuliiaNivina commented on src/sass/components/_contacts.scss
> +                #f9f7f7 50%,
Тут зараз немає сенсу робити прозорість, щоб це працювало на фоні боді потрібні мороженки

2022-12-22 09:01 UTC, YuliiaNivina commented
На секції ревью немає падінгів

2022-12-22 09:03 UTC, IgorPetrenko72 commented on src/sass/components/_contacts.scss
> +                #f9f7f7 50%,
я теж спробував поставити прозорість - не працює!
-на фоні боді потрібні мороженки- можливо спробувати об'єднати ревью та коньакти в один дів та поставити мороженки.

2022-12-22 09:10 UTC, IgorPetrenko72 commented on src/partials/contacts.html
> +  </div>
можу змарджити, а потім нову гілку та поправимо

2022-12-22 09:15 UTC, IgorPetrenko72 commented on src/partials/contacts.html
> +  </div>
в пул реквесті висить щє гілка advantages, але вона недороблена.
Віка на комп скаржится знову.
Я цю гілку теж додаю у мейн та будемо бачити усю сторінку.

2022-12-22 09:23 UTC, IgorPetrenko72 approved these changes

2022-12-22 10:09 UTC, merged